version: 1
cell:
  name: test-cell
  id: test-cell-1
  namespace: celluler
  transporter:
    type: TCP
    options:
      port: 0
      udpDiscovery: true
      udpReusePort: true
      udpPeriod: 30
  services:
    enabled:
      - nucleus
    config:
      nucleus:
        storage: memory
        encryption: true
  logging:
    level:
      METRICS: warn
      TRACING: warn
      REGISTRY: warn
      DISCOVERER: warn
      TRANSIT: warn
      "**": info
    output:
      - type: Console
        options:
          formatter: full
          colors: true
          moduleColors: false
          autoPadding: false
      - type: File
        options:
          formatter: json
          folder: ./logs
          filename: cell-{date}.log
          eol: "\n"
          interval: 1000
  performance:
    requestTimeout: 5000
    maxCallLevel: 100
    heartbeatInterval: 5
    heartbeatTimeout: 15
  security:
    tls: false
    auth: false
    encryption: true
  registry:
    strategy: RoundRobin
    preferLocal: true
  circuitBreaker:
    enabled: true
    threshold: 0.5
    windowTime: 60
    minRequestCount: 20
    halfOpenTime: 10000
  bulkhead:
    enabled: true
    concurrency: 10
    maxQueueSize: 100
  metrics:
    enabled: true
    reporter:
      - Console
  tracing:
    enabled: true
    exporter:
      - Console
  cacher:
    type: Memory
    options:
      max: 1000
  serializer:
    type: JSON
    options: {}
  middlewares: []
  metadata: {} 