extends: base.config.yaml

cell:
  id: cell-prod-${process.pid}
  name: cell-prod
  logger:
    type: Console
    options:
      level: warn
      colors: false
      moduleColors: false
      formatter: short
      autoPadding: false
  metrics:
    reporter: ['Prometheus']
  tracing:
    exporter: ['Jaeger']
  cacher:
    type: Redis
    options:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      max: 10000 