title: Celluler Documentation
description: Documentation for the Celluler decentralized microservices ecosystem
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
nav:
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Services: services.md
  - Networking: networking.md
  - AI Integration: ai.md
  - API Reference: api.md
  - Contributing: contributing.md

# Site settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - .gitignore
  - .git
  - README.md

# Just the Docs theme settings
just_the_docs:
  # Enable dark mode
  dark_mode_toggle: true
  # Enable system preference detection
  dark_mode_system_preference: true
  # Enable search
  search: true
  # Enable navigation
  nav_fold: true
  # Enable back to top button
  back_to_top: true

# Custom CSS
stylesheets:
  - /assets/css/custom.css 