title: Celluler Documentation
description: Documentation for the Celluler decentralized microservices ecosystem
theme: jekyll-theme-hacker

# Navigation
nav:
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Services: services.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md

# Site settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - .gitignore
  - .git
  - README.md
  - vendor

# Custom CSS
stylesheets:
  - assets/css/custom.css
